spring:

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/wtm
    username: admin
    password: admin

  jpa:
    hibernate:
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    hibernate.hbm2ddl.auto: create-drop
